version: "3"

volumes:
  things_db_data:
  emqx_license:

services:

  things:
    build: ../things
    depends_on:
      - things_db
      - emqx
    environment:
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_HOST_PORT: 1883
      MQTT_BROKER_HOST_STATUS_PORT: 8081
      PGHOST: things_db
      PGPORT: 5432
      PGDATABASE: ${THINGS_DB_NAME}
      PGUSER: ${THINGS_DB_USERNAME}
      PGPASSWORD: ${THINGS_DB_PASSWORD}
      PGCONNECT_TIMEOUT: 5
    ports:
      - 8082:8080

  things_db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - things_db_data:/var/lib/postgresql/data
      - ./things_db_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${THINGS_DB_NAME}
      POSTGRES_USER: ${THINGS_DB_USERNAME}
      POSTGRES_PASSWORD: ${THINGS_DB_PASSWORD}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  emqx:
    image: emqx/emqx:4.3.11
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=emqx.broker.io"
      - "EMQX_CLUSTER__DISCOVERY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=emqx@emqx.broker.io"
      - "EMQX_ZONE__EXTERNAL__RETRY_INTERVAL=2s"
      - "EMQX_MQTT__MAX_TOPIC_ALIAS=10"
    volumes:
      - emqx_license:/opt/emqx/etc/emqx.lic
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx_ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883   # MQTT
      - 8081:8081   # Health check
      - 18083:18083 # Management
