# Be sure to update the environments in your "".vscode/setting.json"
#
#    "dev": {
#         "host": "https://blablabla.com",
#         "token": "yourToken"
#     },
#
# Tutorial:
# https://www.youtube.com/watch?v=RcxvrhQKv8I
#

@host = http://localhost:8082
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJSb2xlIjoiYWRtaW4iLCJleHAiOjE2NDcxNjU2NzAsImlhdCI6MTY0NzE2MjA3MCwiaXNzIjoiZGV2X2xvY2FsIiwic3ViIjoiMCJ9.jR7d54uGXzGTF_R67RofguCMrTq7m7-VW1kq5vaoNSc
@userId = 2c2b157c-79d9-4ee6-8013-bb650a56cca4
@userEmail = quidonc@nimportequoi.com
@userPassword = superStrongPassword
@userFullName = Thibaux Toizossi
@userNewFullName = Jacques Cellere
@userMetadata = {}
@adminEmail = admin@bariot.com
@adminPassword = xOJNmAWTezOArlcvJ9vw6Vb5xK6wapcCw1lPIJCuAxweQYSkDTTHiMe2UXkxMCS

### GET user by id
GET {{host}}/{{userId}}
Authorization: {{token}}

### Create a user
POST {{host}}/
Authorization: {{token}}
content-type: application/json

{
"FullName": "{{userFullName}}",
"Email" : "{{userEmail}}",
"Password" : "{{userPassword}}"
} 

### Update a user
PUT {{host}}/{{userId}}
Authorization: {{token}}
content-type: application/json

{
"FullName": "{{userNewFullName}}",
"Email" : "{{userEmail}}"
}

### Delete a user
DELETE {{host}}/{{userId}}
Authorization: {{token}}
{}

### Login a user
POST {{host}}/login
Authorization: {{token}}
content-type: application/json

{
"Email" : "{{userEmail}}",
"Password": "{{userPassword}}"
}


### Login a admin
POST {{host}}/login/admin
Authorization: {{token}}
content-type: application/json

{
"Email" : "{{adminEmail}}",
"Password": "{{adminPassword}}"
}
