// Command to generate grpc
// $ protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative .\thing.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: things.proto

package things

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserOfThingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThingId string `protobuf:"bytes,1,opt,name=thingId,proto3" json:"thingId,omitempty"`
}

func (x *GetUserOfThingRequest) Reset() {
	*x = GetUserOfThingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_things_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserOfThingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOfThingRequest) ProtoMessage() {}

func (x *GetUserOfThingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_things_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOfThingRequest.ProtoReflect.Descriptor instead.
func (*GetUserOfThingRequest) Descriptor() ([]byte, []int) {
	return file_things_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserOfThingRequest) GetThingId() string {
	if x != nil {
		return x.ThingId
	}
	return ""
}

type GetUserOfThingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *GetUserOfThingResponse) Reset() {
	*x = GetUserOfThingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_things_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserOfThingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOfThingResponse) ProtoMessage() {}

func (x *GetUserOfThingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_things_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOfThingResponse.ProtoReflect.Descriptor instead.
func (*GetUserOfThingResponse) Descriptor() ([]byte, []int) {
	return file_things_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserOfThingResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_things_proto protoreflect.FileDescriptor

var file_things_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x31, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x4f, 0x66, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x5b, 0x0a, 0x06, 0x54,
	0x68, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x51, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x4f, 0x66, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x2e, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x69, 0x6e, 0x63,
	0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x2f, 0x42, 0x61, 0x72, 0x69, 0x6f, 0x74, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x68,
	0x69, 0x6e, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_things_proto_rawDescOnce sync.Once
	file_things_proto_rawDescData = file_things_proto_rawDesc
)

func file_things_proto_rawDescGZIP() []byte {
	file_things_proto_rawDescOnce.Do(func() {
		file_things_proto_rawDescData = protoimpl.X.CompressGZIP(file_things_proto_rawDescData)
	})
	return file_things_proto_rawDescData
}

var file_things_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_things_proto_goTypes = []interface{}{
	(*GetUserOfThingRequest)(nil),  // 0: things.GetUserOfThingRequest
	(*GetUserOfThingResponse)(nil), // 1: things.GetUserOfThingResponse
}
var file_things_proto_depIdxs = []int32{
	0, // 0: things.Things.GetUserOfThing:input_type -> things.GetUserOfThingRequest
	1, // 1: things.Things.GetUserOfThing:output_type -> things.GetUserOfThingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_things_proto_init() }
func file_things_proto_init() {
	if File_things_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_things_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserOfThingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_things_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserOfThingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_things_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_things_proto_goTypes,
		DependencyIndexes: file_things_proto_depIdxs,
		MessageInfos:      file_things_proto_msgTypes,
	}.Build()
	File_things_proto = out.File
	file_things_proto_rawDesc = nil
	file_things_proto_goTypes = nil
	file_things_proto_depIdxs = nil
}
