# Be sure to update the environments in your "".vscode/setting.json"
#
#    "dev": {
#         "host": "https://blablabla.com",
#         "token": "yourToken"
#     },
#
# Tutorial:
# https://www.youtube.com/watch?v=RcxvrhQKv8I
#

@host = http://localhost:8083
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJSb2xlIjoidXNlciIsImV4cCI6MTY0NTUzNDYxMiwiaWF0IjoxNjQ1NDQ4MjEyLCJpc3MiOiJkZXZfbG9jYWwiLCJzdWIiOiJhODUzMTA2OC0yODE5LTQzOGUtODk1OS1lMDYwMjNlNWFkYWMifQ.I4EHSJY706LY8JAsSLzsrjw17YZ0DoA4J59e30EObS4
@thingId = db3ae8a0-c771-4557-8340-cbcabdf5b57b
@thingName = Device1
@thingNewName = Device2
@thingKey = 1234567890
@thingUserId = d91112eb-c44a-4fe3-ab84-89e46880e2cd
@thingMetadata = {}

### GET Thing by id
GET {{host}}/{{thingId}}
Authorization: {{token}}

### Create a thing
POST {{host}}/
Authorization: {{token}}
content-type: application/json

{
"Name": "{{thingName}}",
"Key" : "{{thingKey}}"
} 

### Update a thing
PUT {{host}}/{{thingId}}
Authorization: {{token}}
content-type: application/json

{
"Name": "{{thingNewName}}",
"Key" : "{{thingKey}}"
}

### Delete a thing
Delete {{host}}/{{thingId}}
Authorization: {{token}}
