# Be sure to update the environments in your "".vscode/setting.json"
#
#    "dev": {
#         "host": "https://blablabla.com",
#         "userToken": "yourToken"
#     },
#
# Tutorial:
# https://www.youtube.com/watch?v=RcxvrhQKv8I
#

@host = http://localhost:8083
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJSb2xlIjoidXNlciIsImV4cCI6MTY0NzI1MDY5NiwiaWF0IjoxNjQ3MTY0Mjk2LCJpc3MiOiJkZXZfbG9jYWwiLCJzdWIiOiIyYzJiMTU3Yy03OWQ5LTRlZTYtODAxMy1iYjY1MGE1NmNjYTQifQ.70q-lNSe7CO9VcC9ETralffUfMczyS0sGcBussp6Bto
@thingId = b14f3158-b9dd-4315-b7e2-fbcf4090bfe7
@thingName = Device1
@thingNewName = Device2
@thingKey = 1234567890
@thingMetadata = {}

### GET Thing by id
GET {{host}}/{{thingId}}
Authorization: {{userToken}}

### Create a thing
POST {{host}}/
Authorization: {{userToken}}
content-type: application/json

{
"Name": "{{thingName}}",
"Key" : "{{thingKey}}"
} 

### Update a thing
PUT {{host}}/{{thingId}}
Authorization: {{userToken}}
content-type: application/json

{
"Name": "{{thingNewName}}",
"Key" : "{{thingKey}}"
}

### Delete a thing
DELETE {{host}}/{{thingId}}
Authorization: {{userToken}}

### Get a thing Token
GET {{host}}/{{thingId}}/token
Authorization: {{userToken}}
